### ISSUE TITLE
Move scionLab.sh and update_gen.py to scion-utilities? / Aka: Repository for SCION attachment points?

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-box#16]
Perhaps it is a bit misleading that scionLab.sh and update_gen.py belong to the scion-box repository. Maybe we need another repository called scion-ap with all the code related to SCION attachment points.

**Comment by matzf** [comment]
This will be addressed by merging different SCIONLab related repositories into a single one, as discussed on Monday.
