### ISSUE TITLE
update_gen.py fails when local gen folder and coordinator differ

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-box#28]
`update_local_gen()` inside `update_gen.py` fails in case the local gen folder and the ASes stored in the SCION coordinator differ. Specifically, `request_server` throws a `missed pk value` error for AS configurations that don't exist on the coordinator side. See also https://github.com/netsec-ethz/scion-coord/issues/168

Expected behavior: `update_gen.py` should ignore ASes from the local gen folder that do not exist in the coordinator and leave them untouched.

**Comment by mlegner** [comment]
The coordinator error is addressed by https://github.com/netsec-ethz/scion-coord/pull/169.

**Comment by matzf** [comment]
This issue appears to have been fixed.
