### ISSUE TITLE
update_gen should restart SCION iff the topology file has changed

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-box#34]
Right now, it will restart if there are pending changes, independently of whether those changes provoked changes in the topology file or not.
E.g. right now due to another bug, update_gen is not modifying the topology file, nor telling the Coordinator to mark the change as processed, and it keeps restarting SCION every time we run update_gen in the attachment points.

**Comment by mlegner** [comment]
This has been fixed by #36.
