### ISSUE TITLE
Full sync or delta sync?

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-box#41]
We have to decide how to instruct the APs to run a full sync or a (up to now) tradicional delta sync.
We have several options:
- Two timers in AP: one for delta sync, the other for the full one. How do we exclude simultaneous runs?
- One timer, static condition: the script checks a condition (time of day, times since last full sync) and chooses one mode
- Coordinator decides: a condition evaluated in the Coordinator that tells the AP it should run full or delta sync.
- Others?

**Comment by matzf** [comment]
The only point in favor of delta sync that I can see is the reduced bandwidth -- however, given that the data size for a full sync is in the order of a few dozen kilobytes and is performed relatively infrequently, I can't see bandwidth to actually be a problem (even if the number of connected ASes is increased dramatically...).
I would argue to always use full sync and remove the logic for the delta sync.

**Comment by juagargi** [comment]
It was decided in #50 to remove the delta sync feature.
