### ISSUE TITLE
Support for multiple attachment points on one host

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scion-box#44]
The `scionlabtesting` machine runs four ASes in two ISDs, with one of the ASes in each ISD being a SCIONLab attachment points (APs). I have observed at least two issues with this setup:
* the initial `supervisor.conf` for the sciond and certificate-server use the `default.sock` which will clash because both AP-ASes use this; I don't know where the initial configuration is obtained from. Is it from scion-web?
* the port for the internal addresses used by the border routers can clash, as they are based only on the client-AS-number.

Not sure whether this issue should rather be in scion-coord.

Some further issues with running multiple APs on one host are addressed in #42.

**Comment by matzf** [comment]
The issue with the port for the internal addresses of the BR may disappear in the future, as support for multiple internal addresses has been removed in scionproto/scion.

**Comment by juagargi** [comment]
There is also another issue, as the update_gen script uses one IP address per invocation: we don't know which tunnel interface corresponds to which AP in advance. I will work into sending this piece of info from the Coordinator and remove the parameter from the command line arguments.
