### ISSUE TITLE
update_gen should not touch supervisord.conf

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-box#47]
We need the prometheus flag to be `-prom "127.0.0.1:blah", but update_gen keeps changing it.
This is needed for the deployment of 2SMS (our monitoring solution).

**Comment by matzf** [comment]
Where does this setting come from in the first place, i.e. how was it originally configured?

**Comment by juagargi** [comment]
I guess it was originally configured via scion-web. For 2SMS we will need to spawn the processes with `-prom 127.0.0.1', and we had changed the `supervisord.conf` files manually to test it.
But, every time there is a change in the topology, it seems we also re-generate the `supervisord.conf` files, and we overwrite this line. 
With the new coordinator I guess we will send all the topology information to the APs, probably including the settings for prometheus, so we'd need a quick fix for the interim.

**Comment by matzf** [comment]
Ok. Just to clarify my understanding, the IP/port set with the `-prom` flag needs to match an entry in the scraper's configuration file, right? Will the configuration of the scrapers have to be generated by the (new) scionlab coordinator as well?

**Comment by juagargi** [comment]
The `-prom` setting will be fixed to `-prom 127.0.0.1` for every service in every AS.
The configuration of the monitoring endpoints (this is new and not yet deployed anywhere) will have to be generated by the new coordinator, but this is open to discussion, i.e. do we configure our infrastructure monitoring using the coordinator? or independently?
